export const resourceManifest = [
  {
    id: "coins",
    label: "Coins",
    color: "#e1b44f",
    description: "Construction budget and guest revenue.",
  },
  {
    id: "lumber",
    label: "Lumber",
    color: "#9b7044",
    description: "Primary material for buildings, paths, and fences.",
  },
  {
    id: "vegetables",
    label: "Vegetables",
    color: "#6caa43",
    description: "Ingredient for herbivore feed and medicine.",
  },
  {
    id: "meat",
    label: "Meat",
    color: "#c65f46",
    description: "Carnivore supply used by specialist habitats.",
  },
  {
    id: "fish",
    label: "Fish",
    color: "#45a6b7",
    description: "Wetlands and aquatic animal supply.",
  },
  {
    id: "animal_feed",
    label: "Animal Feed",
    color: "#d99652",
    description: "Prepared feed used by animal habitats.",
  },
  {
    id: "medicine",
    label: "Medicine",
    color: "#d66b7a",
    description: "Veterinary supply used to stabilize animal health.",
  },
  {
    id: "water",
    label: "Water",
    color: "#4f9ad8",
    description: "Habitat and guest-service utility resource.",
  },
  {
    id: "visitors",
    label: "Visitors",
    color: "#7cc8c3",
    description: "Guests available to spend at zoo attractions.",
  },
  {
    id: "research_points",
    label: "Research",
    color: "#8d7bd8",
    description: "Progress used for tech nodes and upgrades.",
  },
  {
    id: "reputation",
    label: "Reputation",
    color: "#f0c769",
    description: "Zoo reputation and level progress.",
  },
  {
    id: "conservation_points",
    label: "Conservation",
    color: "#77b67a",
    description: "Long-term conservation success from habitats.",
  },
];

export const buildingManifest = [
  {
    kind: "customer_entry",
    label: "Customer Entry",
    category: "entry",
    size: [1.4, 1.1],
    buildDuration: 0,
    requiredWorkers: 0,
    cost: "Starter",
    swatch: "#bfc1ad",
    icon: "gate",
    gltf: null,
  },
  {
    kind: "ticket_booth",
    label: "Ticket Booth",
    category: "guest",
    size: [1.1, 0.95],
    buildDuration: 6,
    requiredWorkers: 1,
    cost: "24 coins, 12 lumber",
    swatch: "#4a8190",
    icon: "ticket",
    gltf: null,
  },
  {
    kind: "guest_plaza",
    label: "Guest Plaza",
    category: "guest",
    size: [1.8, 1.25],
    buildDuration: 5,
    requiredWorkers: 0,
    cost: "30 coins, 18 lumber",
    swatch: "#bfc1ad",
    icon: "plaza",
    gltf: null,
  },
  {
    kind: "restroom",
    label: "Restroom",
    category: "guest",
    size: [1.25, 1.05],
    buildDuration: 10,
    requiredWorkers: 1,
    cost: "35 coins, 8 water",
    swatch: "#6f93a1",
    icon: "water",
    gltf: null,
  },
  {
    kind: "snack_kiosk",
    label: "Snack Kiosk",
    category: "guest",
    size: [1.25, 1.05],
    buildDuration: 12,
    requiredWorkers: 1,
    cost: "40 coins, 10 lumber",
    swatch: "#d99652",
    icon: "food",
    gltf: null,
  },
  {
    kind: "souvenir_stall",
    label: "Souvenir Stall",
    category: "guest",
    size: [1.35, 1.05],
    buildDuration: 15,
    requiredWorkers: 1,
    cost: "55 coins, 16 lumber",
    swatch: "#8d7bd8",
    icon: "shop",
    gltf: null,
  },
  {
    kind: "zookeeper_house",
    label: "Zookeeper House",
    category: "staff",
    size: [1.55, 1.15],
    buildDuration: 0,
    requiredWorkers: 0,
    cost: "Starter",
    swatch: "#936b45",
    icon: "staff",
    gltf: null,
  },
  {
    kind: "keeper_kitchen",
    label: "Keeper Kitchen",
    category: "staff",
    size: [1.55, 1.15],
    buildDuration: 12,
    requiredWorkers: 1,
    cost: "35 coins, 18 lumber",
    swatch: "#d9d2b8",
    icon: "kitchen",
    gltf: null,
  },
  {
    kind: "feed_shed",
    label: "Feed Shed",
    category: "staff",
    size: [1.3, 0.95],
    buildDuration: 5,
    requiredWorkers: 0,
    cost: "15 lumber",
    swatch: "#936b45",
    icon: "storage",
    gltf: null,
  },
  {
    kind: "vet_clinic",
    label: "Vet Clinic",
    category: "staff",
    size: [1.6, 1.2],
    buildDuration: 18,
    requiredWorkers: 1,
    cost: "60 coins, 18 lumber",
    swatch: "#d66b7a",
    icon: "medical",
    gltf: null,
  },
  {
    kind: "maintenance_shed",
    label: "Maintenance Shed",
    category: "staff",
    size: [1.45, 1.05],
    buildDuration: 14,
    requiredWorkers: 1,
    cost: "45 coins, 20 lumber",
    swatch: "#8a6646",
    icon: "tool",
    gltf: null,
  },
  {
    kind: "research_office",
    label: "Research Office",
    category: "staff",
    size: [1.7, 1.2],
    buildDuration: 20,
    requiredWorkers: 1,
    cost: "80 coins, 24 lumber",
    swatch: "#8d7bd8",
    icon: "research",
    gltf: null,
  },
  {
    kind: "animal_area",
    label: "Animal Area",
    category: "habitat",
    size: [2.8, 2.2],
    buildDuration: 18,
    requiredWorkers: 1,
    cost: "50 coins, 20 lumber",
    swatch: "#78aa5b",
    icon: "habitat-zone",
    gltf: null,
    requiresPath: true,
    allowsAttachedFences: true,
  },
  {
    kind: "savanna_habitat",
    label: "Savanna Habitat",
    category: "habitat",
    size: [3.6, 2.55],
    buildDuration: 24,
    requiredWorkers: 2,
    cost: "70 coins, 28 lumber",
    swatch: "#d4ba74",
    icon: "habitat",
    gltf: null,
  },
  {
    kind: "wetlands_habitat",
    label: "Wetlands Habitat",
    category: "habitat",
    size: [3.5, 2.45],
    buildDuration: 24,
    requiredWorkers: 2,
    cost: "70 coins, 28 lumber",
    swatch: "#45a6b7",
    icon: "wetlands",
    gltf: null,
  },
  {
    kind: "aviary",
    label: "Aviary",
    category: "habitat",
    size: [3.0, 2.3],
    buildDuration: 24,
    requiredWorkers: 2,
    cost: "70 coins, 28 lumber",
    swatch: "#77b67a",
    icon: "aviary",
    gltf: null,
  },
  {
    kind: "reptile_house",
    label: "Reptile House",
    category: "habitat",
    size: [2.8, 2.2],
    buildDuration: 24,
    requiredWorkers: 2,
    cost: "70 coins, 28 lumber",
    swatch: "#a78358",
    icon: "reptile",
    gltf: null,
  },
];

export const pathManifest = [
  { kind: "guest_path", label: "Guest Path", swatch: "#c7b889", icon: "path" },
  { kind: "service_path", label: "Service Path", swatch: "#a99d82", icon: "service-path" },
];

export const areaManifest = [
  { kind: "buildable_grass", label: "Buildable Grass", swatch: "#77a859", icon: "area" },
  { kind: "habitat_zone", label: "Habitat Zone", swatch: "#6caa43", icon: "habitat-zone" },
  { kind: "guest_zone", label: "Guest Zone", swatch: "#e1b44f", icon: "guest-zone" },
  { kind: "staff_zone", label: "Staff Zone", swatch: "#45a6b7", icon: "staff-zone" },
];

export const fenceManifest = [
  { kind: "wood_fence", label: "Wood Fence", swatch: "#8a6646", icon: "fence" },
  { kind: "steel_fence", label: "Steel Fence", swatch: "#8f9aa2", icon: "steel-fence" },
  { kind: "glass_barrier", label: "Glass Barrier", swatch: "#9ed1da", icon: "glass" },
];
